name: Security Pipeline

on:
  push:
  pull_request:

jobs:
  bandit_scan:
    name: Run Bandit (Python SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Bandit
        run: pip install --upgrade pip bandit

      - name: Run Bandit Scan (fail on HIGH)
        run: |
          bandit -r . -f json -o bandit_report.json -lll

  trivy_scan:
    name: Run Trivy (Filesystem & Container Scan)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy Filesystem Scan (fail on HIGH/CRITICAL)
        run: trivy fs --severity HIGH,CRITICAL --exit-code 1 --format json --output trivy_fs.json .

  upload_reports:
    name: Upload Security Reports
    needs: [bandit_scan, trivy_scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit_report.json
            trivy_fs.json
          if-no-files-found: warn
